// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7j1zfnIN17J2TH-s3shdI4webihPPCBo',
    appId: '1:726418298579:web:8fa04abd9291d952c7e626',
    messagingSenderId: '726418298579',
    projectId: 'chat-bot-cda7e',
    authDomain: 'chat-bot-cda7e.firebaseapp.com',
    storageBucket: 'chat-bot-cda7e.firebasestorage.app',
    measurementId: 'G-XLGP2EFH2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRjOjo5f_B_ufSCqKoUqRhEOEmOBJi6Cg',
    appId: '1:726418298579:android:3f8820685d7adedac7e626',
    messagingSenderId: '726418298579',
    projectId: 'chat-bot-cda7e',
    storageBucket: 'chat-bot-cda7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBSY1XObtYSTSMoWfGZ5H9I6dzXaUgaYM',
    appId: '1:726418298579:ios:2c77ec55ed90d74dc7e626',
    messagingSenderId: '726418298579',
    projectId: 'chat-bot-cda7e',
    storageBucket: 'chat-bot-cda7e.firebasestorage.app',
    iosBundleId: 'com.example.chatbot',
  );
}
